Models/auth.py
from flask_jwt_extended import JWTManager

jwt = JWTManager()

def init_auth(app):
    jwt.init_app(app)

app.py
from config import server
from database import db
from Models import auth 

#To use routes
from routes.main_routes import main
from routes.auth_routes import auth as user_auth

app = server()
app.register_blueprint(main)
app.register_blueprint(user_auth)

auth.init_auth(app)

if __name__ == "__main__":
    with app.app_context():
        db.create_all()
    app.run(debug = True, host="0.0.0.0")

routes/auth_routes.py
from flask import Blueprint, render_template, request, redirect, url_for, flash
from Models.userModel import UserModel
from database import db
from werkzeug.security import generate_password_hash, check_password_hash
from flask_jwt_extended import create_access_token

auth = Blueprint('auth', __name__)

@auth.route('/register', methods=['GET', 'POST'])
def register():
    if request.method == 'POST':
        name = request.form['name']
        email = request.form['email']
        password = request.form['password']
        if UserModel.query.filter_by(name=name).first():
            flash('The user already exist')
            return redirect(url_for('auth.register'))
        user = UserModel(
            name=name,
            email=email,
            password_hash=generate_password_hash(password)
        )
        db.session.add(user)
        db.session.commit()
        flash('User Created Succesfully')
        return redirect(url_for('auth.login'))
    return render_template('auth/register.html')

@auth.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        name = request.form['name']
        password = request.form['password']
        user = UserModel.query.filter_by(name=name).first()
        if user and check_password_hash(user.password_hash, password):
            access_token = create_access_token(identity=user.id)
            flash('Login success')
            return render_template('images/images.html', token=access_token)
        else:
            flash('Incorrect user or password')
    return render_template('auth/login.html')

routes/main_routes.py
from flask import Blueprint, render_template, request, redirect, url_for, send_from_directory, flash
import os
from werkzeug.utils import secure_filename
from Models.imagesModel import Images
from database import db

from flask_jwt_extended import jwt_required, get_jwt_identity

import cv2 

main = Blueprint('main', __name__)

@main.route("/")
def index():
    return render_template("index.html")

#Image processing routes
UPLOAD_FOLDER = 'uploads'
ALLOWED_EXTENSIONS = {'png', 'jpg', 'jpeg', 'gif'}

def allowed_file(filename):
    return '.' in filename and filename.rsplit('.', 1)[1].lower() in ALLOWED_EXTENSIONS

@jwt_required()
@main.route("/Processing", methods=["GET", "POST"])
def processing():
    current_user_id = get_jwt_identity() #To Know who use this process
    if request.method == "POST":
        if 'file' not in request.files:
            flash('No file part')
            return redirect(request.url)
        file = request.files['file']
        if file.filename == '':
            flash('No selected file')
            return redirect(request.url)
        if file and allowed_file(file.filename):
            filename = secure_filename(file.filename)
            filename = f"original_{filename}"
            os.makedirs(UPLOAD_FOLDER, exist_ok=True)
            file.save(os.path.join(UPLOAD_FOLDER, filename))
            # Guardar en la base de datos
            image = Images(filename=filename)
            db.session.add(image)
            db.session.commit()
            flash('Image uploaded successfully!')
            #return redirect(url_for('main.index'))
            return render_template("images/ProcessingMenu.html", filename=filename)
        else:
            flash('Invalid file type. Allowed formats (.png, .jpg, .jpeg, .gif)')
    return render_template("images/images.html")

@jwt_required()
@main.route("/savedImages")
def list_images():
    current_user_id = get_jwt_identity()
    try:
        images = Images.query.all()
        if not images:
            message = "Don't have saved images"
        else:
            message = None
    except Exception as e:
        images = []
        message = "Data base or table doesn't exist"
    return render_template("images/list_saved_images.html", images=images)

@jwt_required()
@main.route('/uploads/<filename>')
def download_image(filename):
    current_user_id = get_jwt_identity()
    return send_from_directory('uploads', filename, as_attachment=True)

@jwt_required()
@main.route('/rotate_image', methods=['POST'])
def rotate_image():
    current_user_id = get_jwt_identity()
    filename = request.form['filename']
    filepath = os.path.join(UPLOAD_FOLDER, filename)
    img = cv2.imread(filepath)
    if img is not None:
        rotated = cv2.rotate(img, cv2.ROTATE_90_CLOCKWISE)
        processed_filename = f"rotated_{filename}"
        processed_path = os.path.join(UPLOAD_FOLDER, processed_filename)
        cv2.imwrite(processed_path, rotated)
        flash('Imagen rotada correctamente.')
        return render_template("images/ProcessingMenu.html", filename=processed_filename)
    else:
        flash('No se pudo procesar la imagen.')
        return redirect(url_for('main.processing'))

@jwt_required() 
@main.route('/grayscale_image', methods=['POST'])
def grayscale_image():
    current_user_id = get_jwt_identity()
    filename = request.form['filename']
    filepath = os.path.join(UPLOAD_FOLDER, filename)
    img = cv2.imread(filepath)
    if img is not None:
        gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
        processed_filename = f"gray_{filename}"
        processed_path = os.path.join(UPLOAD_FOLDER, processed_filename)
        cv2.imwrite(processed_path, gray)
        flash('Imagen convertida a escala de grises.')
        return render_template("images/ProcessingMenu.html", filename=processed_filename)
    else:
        flash('No se pudo procesar la imagen.')
        return redirect(url_for('main.processing'))

@jwt_required()
@main.route('/save_processed_image', methods=['POST'])
def save_processed_image():
    current_user_id = get_jwt_identity()
    filename = request.form['filename']
    processed_filename = f"processed_{filename}"
    original_path = os.path.join(UPLOAD_FOLDER, filename)
    processed_path = os.path.join(UPLOAD_FOLDER, processed_filename)

    if not os.path.exists(processed_path):
        import shutil
        shutil.copyfile(original_path, processed_path)
    
    if Images.query.filter_by(filename=processed_filename).first():
        flash('The image is already saved.')
    else:
        image = Images(filename=processed_filename)
        db.session.add(image)
        db.session.commit()
        flash('Save processed image.')
    return render_template("images/ProcessingMenu.html", filename=processed_filename)

@main.route('/borderDetection_image', methods=['POST'])
@jwt_required()
def canny_image():
    current_user_id = get_jwt_identity()
    filename = request.form['filename']
    path = os.path.join(UPLOAD_FOLDER, filename)
    img = cv2.imread(path)
    edges = cv2.Canny(img, 100, 200)
    output = f"canny_{filename}"
    cv2.imwrite(os.path.join(UPLOAD_FOLDER, output), edges)
    flash("Canny edge detection applied.")
    return render_template("images/ProcessingMenu.html", filename=output)

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Image Processing{% endblock %}</title>
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}">
    {% block extra_css %}{% endblock %}
    {% block head %}{% endblock %}
</head>   

<body>
    {% block body %}{% endblock %}
</body>

</html>

templates/images/ProcessingMenu.html
{% extends 'base.html' %}

{% block title %}Image Processing Menu{% endblock %}

{% block body %}
<div style="display: flex; flex-direction: column; align-items: center; justify-content: center; min-height: 60vh;">
    <h2>Image Processing Menu</h2>
    <img src="{{ url_for('main.download_image', filename=filename) }}" alt="Uploaded Image" style="max-width: 400px; margin-bottom: 2rem;">
    
  <div style="display: flex; gap: 1.5rem; margin-bottom: 1.5rem;">
        <form action="{{ url_for('main.rotate_image') }}" method="post">
            <input type="hidden" name="filename" value="{{ filename }}">
            <button type="submit">Rotate Image</button>
        </form>
        <form action="{{ url_for('main.grayscale_image') }}" method="post">
            <input type="hidden" name="filename" value="{{ filename }}">
            <button type="submit">Gray Scale</button>
        </form>
    </div>
    <form action="{{ url_for('main.save_processed_image') }}" method="post">
        <input type="hidden" name="filename" value="{{ filename }}">
        <button type="submit">Save</button>
    </form>

    <div style="margin-top: 2rem;">
        <a href="{{ url_for('main.processing') }}"><button>Back</button></a>
    </div>
</div>
{% endblock %}

templates/images/images.html
<!-- templates/index.html -->
{% extends 'base.html' %}

{% block head %}
<div style="display: flex; flex-direction: column; align-items: center; justify-content: center; min-height: 10vh;">
    <title>Image Processing</title>
    <h1>Image Processing: INBest</h1>
    <h5>Author: Oscar Alberto Gallo Garcia</h5>
</div>
{% endblock %}

{% block body %}
<div style="display: flex; flex-direction: column; align-items: center; justify-content: center; min-height: 10vh;">
    <div style="margin-bottom: 1rem;">
        <a href="{{ url_for('main.list_images') }}">
            <button type="button">View Saved Images</button>
        </a>
    </div>
    <h2>upload the image for processing</h2>
    <form action="{{ url_for('main.processing') }}" method="post" enctype="multipart/form-data">
        <input type="file" name="file" id="fileInput" accept="image/*" required>
        <img id="preview" src="#" alt="Preview" style="display:none; max-width:300px; margin:1rem 0;" />
        <div style="display: flex; justify-content: center; align-items: center; gap: 2rem; margin-top: 1rem;">
            <button type="submit">Upload</button>
            <button type="button" id="cancelBtn">Cancel</button>
        </div>
    </form>

    {% with messages = get_flashed_messages() %}
    {% if messages %}
        <ul>
        {% for message in messages %}
            <li>{{ message }}</li>
        {% endfor %}
        </ul>
    {% endif %}
    {% endwith %}
</div>

<script>
    document.getElementById('fileInput').addEventListener('change', function(event){
        const [file] = event.target.files;
        const preview = document.getElementById('preview');
        if(file){
            preview.src = URL.createObjectURL(file);
            preview.style.display = 'block';
        }else{
            preview.src = '#';
            preview.style.display = 'none';
        }
});
    //Cancel button 
     document.getElementById('cancelBtn').addEventListener('click', function(){
        const fileInput = document.getElementById('fileInput');
        const preview = document.getElementById('preview');
        fileInput.value = '';
        preview.src = '#';
        preview.style.display = 'none';
    });

</script>

{% endblock %}

templates/images/list_saved_images.html
{% extends 'base.html' %}

{% block title %}Saved Images{% endblock %}

{% block body %}
    {% if message %}
        <p>{{ message }}</p>
    {% else %}
        <h1>Saved Images</h1>
        <ul>
            {% for image in images %}
                <li>
                    {{ image.filename }}
                    <button type="button" onclick="showPreview('{{ url_for('main.download_image', filename=image.filename) }}')">Preview</button>
                    <form method="get" action="{{ url_for('main.download_image', filename=image.filename) }}" style="display:inline;">
                        <button type="submit">Descargar</button>
                    </form>
                </li>
            {% endfor %}
        </ul>
        <img id="imagePreview" class="preview-img" src="#" alt="Preview" style="display:none; max-width:400px; margin:1rem auto;" />
    {% endif %}
    <div style="margin-top: 2rem;">
        <a href="{{ url_for('main.processing') }}"><button>Regresar</button></a>
    </div>
    <script>
        function showPreview(imgUrl) {
            var preview = document.getElementById('imagePreview');
            preview.src = imgUrl;
            preview.style.display = 'block';
        }
    </script>
{% endblock %}

templates/index.html
{% extends 'base.html' %}

{% block head %}
<div style="display: flex; flex-direction: column; align-items: center; justify-content: center; min-height: 10vh;">
    <title>Image Processing</title>
    <h1>Image Processing: INBest</h1>
    <h5>Author: Oscar Alberto Gallo Garcia</h5>
</div>
{% endblock %}

{% block body %}
<div style="display: flex; flex-direction: column; align-items: center; justify-content: center; min-height: 10vh;">
    <h6>Welcome to Image Processing</h6>
    <div style="display: flex; gap: 1rem;">
        <a href="{{ url_for('auth.login') }}"><button>Login</button></a>
        <a href="{{ url_for('auth.register') }}"><button>Create User</button></a>
    </div>
</div>
{% endblock %}